general.import = ["/Users/tomi/.config/alacritty/themes/nord.toml"]

[cursor.style]
blinking = "Never"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.8
blur = true

[window.dimensions]
columns = 164
lines = 36

[window.padding]
x = 4
y = 4
