general.import = ["~/.config/alacritty/alacritty.common.toml"]

# macOS-specific settings
[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[window]
decorations = "Full"
opacity = 1
