return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = "BufReadPost",
  opts = {
    ensure_installed = {
      "bash",
      "gitignore",
      "lua",
      "vim",
      "vimdoc",
      "markdown",
      "markdown_inline",
      "yaml",
      "json",
      "html",
      "swift",
      "ruby",
      "python",
      "css",
      "dockerfile",
      "toml",
      "make",
      "plist",
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { "ruby" },
    },
    indent = { enable = true, disable = { "ruby" } },
    autotag = { enable = true },
  },
}
