vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.loaded = 1
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.autopairs_enabled = true
vim.g.have_nerd_font = true
vim.g.mkdp_auto_start = 0
vim.g.user_enable_transparent_background = true
